"""empty message

Revision ID: 2590a96b197a
Revises: 
Create Date: 2023-11-01 12:33:26.062981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2590a96b197a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bytespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bytespace_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bytespace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('user_first_name', sa.String(), nullable=True),
    sa.Column('user_last_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bytespace_id'], ['bytespaces.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['user_first_name'], ['users.first_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_last_name'], ['users.last_name'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bytestreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('bytespace_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bytespace_id'], ['bytespaces.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'bytespace_id', name='uq_name_bytespace_id')
    )
    op.create_table('bytestream_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bytestream_id', sa.Integer(), nullable=True),
    sa.Column('bytespace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('user_first_name', sa.String(), nullable=True),
    sa.Column('user_last_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bytespace_id'], ['bytespaces.id'], ),
    sa.ForeignKeyConstraint(['bytestream_id'], ['bytestreams.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['user_first_name'], ['users.first_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_last_name'], ['users.last_name'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bytestream_users')
    op.drop_table('bytestreams')
    op.drop_table('bytespace_users')
    op.drop_table('bytespaces')
    op.drop_table('users')
    # ### end Alembic commands ###
